### ISSUE TITLE
NoClassDefFoundError Issue on Windows 

### ISSUE THREAD

**Issue by sadeghpro** [profesorfalken/jProcesses#18]
hi
first tnx for this useful library.

when i use this in mac it is ok but on Windows get this error:
java.lang.NoClassDefFoundError: org/jutils/jprocesses/JProcesses

**Comment by profesorfalken** [comment]
Hello!, 

I cannot see it in the stack but I guess that the problem is that you are not using Maven. Instead you have download and used the JAR file.

If you read the Installation text in jProcesses project: https://github.com/profesorfalken/jProcesses you will see that jProcesses needs a library to make WMI queries (needed in Windows in order to get the process list), called WMI4Java.

Could you try to download it?https://repo1.maven.org/maven2/com/profesorfalken/WMI4Java/1.4.2/WMI4Java-1.4.2.jar

And add it to your classpath?

Best regards

**Comment by sadeghpro** [comment]
I add WMI4java to classpath and if reason of this error is that must error like:
java.lang.NoClassDefFoundError: com/profesorfalken/wmi4java/WMI4Java
not:
 java.lang.NoClassDefFoundError: org/jutils/jprocesses/JProcesses
and I use
https://github.com/profesorfalken/profesorfalken.github.io/blob/master/files/jProcesses-1.6.1-jar-with-dependencies.jar?raw=true
but nothing change

**Comment by profesorfalken** [comment]
Hi, 

I have just generated a new fat jar for you with the actual version: 
https://github.com/profesorfalken/profesorfalken.github.io/blob/master/files/jProcesses-1.6.3-jar-with-dependencies.jar?raw=true

Can you check it? If not, it will be useful if you paste here the detailed stack. 
I do not use Windows OS normally so we will have to wait until next week, when I will try to reproduce in my workplace computer.

Best regards

**Comment by sadeghpro** [comment]
it's work.
thanks
